# Shared GraalVM Native Image configuration for bc-tool
Args = -H:+AddAllCharsets \
       --future-defaults=run-time-initialize-security-providers \
       -Djava.security.properties=src/main/resources/java.security.override \
       --enable-url-protocols=https \
       -H:+AllowIncompleteClasspath \
       --initialize-at-run-time=java.awt,javax.swing,sun.awt,sun.font,sun.java2d,sun.swing,com.sun.java.swing,com.intellij.uiDesigner,alg.bc.gui.util.Logger,alg.bc.gui.util.AwtExceptionHandler \
       -H:+JNI \
       --enable-native-access=java.desktop,ALL-UNNAMED \
       --no-fallback \
       -H:+ReportExceptionStackTraces \
       --report-unsupported-elements-at-runtime \
       -H:NativeLinkerOption=/SUBSYSTEM:WINDOWS \
       -H:NativeLinkerOption=/ENTRY:mainCRTStartup \
       -Djava.awt.headless=false \
       -Duser.country=CN \
       -Duser.language=zh \
       -Dawt.useSystemAAFontSettings=on \
       -Dswing.aatext=true \
       -Dsun.java2d.dpiaware=true \
       -Dsun.font.fontmanager=sun.awt.Win32FontManager \
       -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel
ImageName = bc-tool
