package alg.bc.gui.view.viewZuc;

import alg.bc.gui.view.TabZuc;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import lombok.Data;

import javax.swing.*;
import java.awt.*;

@Data
public class ViewZucCipher {
    private JPanel zucCipherPanel;
    private JRadioButton zuc128RadioButton;
    private JRadioButton zuc256RadioButton;
    private JTextArea keyTextArea;
    private JComboBox<String> keyEncodeComboBox;
    private JTextArea ivTextArea;
    private JComboBox<String> ivEncodeComboBox;
    private JTextArea inputTextArea;
    private JComboBox<String> inputEncodeComboBox;
    private JTextArea outputTextArea;
    private JComboBox<String> outputEncodeComboBox;
    private JButton generateKeyButton;
    private JButton generateIvButton;
    private JButton cipherButton;
    private JButton resetButton;
    private JLabel keySizeLabel;
    private JLabel ivSizeLabel;

    public void init(TabZuc parent) {
        cipherButton.setActionCommand("zucCipher");
        cipherButton.addActionListener(parent.getAction());
        resetButton.setActionCommand("resetForm");
        resetButton.addActionListener(parent.getAction());
        generateKeyButton.setActionCommand("generateZucKey");
        generateKeyButton.addActionListener(parent.getAction());
        generateIvButton.setActionCommand("generateZucIv");
        generateIvButton.addActionListener(parent.getAction());

        // ZUC版本切换监听
        zuc128RadioButton.addActionListener(e -> {
            if (zuc128RadioButton.isSelected()) {
                keySizeLabel.setText("密钥(16字节)：");
                ivSizeLabel.setText("IV(16字节)：");
            }
        });
        zuc256RadioButton.addActionListener(e -> {
            if (zuc256RadioButton.isSelected()) {
                keySizeLabel.setText("密钥(32字节)：");
                ivSizeLabel.setText("IV(25字节)：");
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        zucCipherPanel = new JPanel();
        zucCipherPanel.setLayout(new GridLayoutManager(9, 4, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("ZUC版本：");
        zucCipherPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        zuc128RadioButton = new JRadioButton();
        zuc128RadioButton.setSelected(true);
        zuc128RadioButton.setText("ZUC-128");
        zucCipherPanel.add(zuc128RadioButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        zuc256RadioButton = new JRadioButton();
        zuc256RadioButton.setText("ZUC-256");
        zucCipherPanel.add(zuc256RadioButton, new GridConstraints(0, 2, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        keySizeLabel = new JLabel();
        keySizeLabel.setText("密钥(16字节)：");
        zucCipherPanel.add(keySizeLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        keyTextArea = new JTextArea();
        keyTextArea.setLineWrap(true);
        zucCipherPanel.add(keyTextArea, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 50), null, 0, false));
        keyEncodeComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("HEX");
        defaultComboBoxModel1.addElement("BASE64");
        keyEncodeComboBox.setModel(defaultComboBoxModel1);
        zucCipherPanel.add(keyEncodeComboBox, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        generateKeyButton = new JButton();
        generateKeyButton.setText("生成密钥");
        zucCipherPanel.add(generateKeyButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ivSizeLabel = new JLabel();
        ivSizeLabel.setText("IV(16字节)：");
        zucCipherPanel.add(ivSizeLabel, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ivTextArea = new JTextArea();
        ivTextArea.setLineWrap(true);
        zucCipherPanel.add(ivTextArea, new GridConstraints(3, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 50), null, 0, false));
        ivEncodeComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        defaultComboBoxModel2.addElement("HEX");
        defaultComboBoxModel2.addElement("BASE64");
        ivEncodeComboBox.setModel(defaultComboBoxModel2);
        zucCipherPanel.add(ivEncodeComboBox, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        generateIvButton = new JButton();
        generateIvButton.setText("生成IV");
        zucCipherPanel.add(generateIvButton, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("输入数据：");
        zucCipherPanel.add(label2, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        inputTextArea = new JTextArea();
        inputTextArea.setLineWrap(true);
        zucCipherPanel.add(inputTextArea, new GridConstraints(5, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 50), null, 0, false));
        inputEncodeComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel3 = new DefaultComboBoxModel();
        defaultComboBoxModel3.addElement("UTF-8");
        defaultComboBoxModel3.addElement("HEX");
        defaultComboBoxModel3.addElement("BASE64");
        inputEncodeComboBox.setModel(defaultComboBoxModel3);
        zucCipherPanel.add(inputEncodeComboBox, new GridConstraints(5, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("输出数据：");
        zucCipherPanel.add(label3, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        outputTextArea = new JTextArea();
        outputTextArea.setLineWrap(true);
        zucCipherPanel.add(outputTextArea, new GridConstraints(6, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 50), null, 0, false));
        outputEncodeComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel4 = new DefaultComboBoxModel();
        defaultComboBoxModel4.addElement("HEX");
        defaultComboBoxModel4.addElement("BASE64");
        defaultComboBoxModel4.addElement("UTF-8");
        outputEncodeComboBox.setModel(defaultComboBoxModel4);
        zucCipherPanel.add(outputEncodeComboBox, new GridConstraints(6, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cipherButton = new JButton();
        cipherButton.setText("加密/解密");
        zucCipherPanel.add(cipherButton, new GridConstraints(8, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        resetButton = new JButton();
        resetButton.setText("重置");
        zucCipherPanel.add(resetButton, new GridConstraints(8, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return zucCipherPanel;
    }

}
