package alg.bc.gui.view.viewZuc;

import alg.bc.gui.view.TabZuc;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import lombok.Data;

import javax.swing.*;
import java.awt.*;

@Data
public class ViewZucMac {
    private JPanel zucMacPanel;
    private JRadioButton zuc128RadioButton;
    private JRadioButton zuc256RadioButton;
    private JTextArea keyTextArea;
    private JComboBox<String> keyEncodeComboBox;
    private JTextArea ivTextArea;
    private JComboBox<String> ivEncodeComboBox;
    private JTextArea dataTextArea;
    private JComboBox<String> dataEncodeComboBox;
    private JTextArea macTextArea;
    private JComboBox<String> macEncodeComboBox;
    private JButton generateKeyButton;
    private JButton generateIvButton;
    private JButton macButton;
    private JButton resetButton;
    private JLabel keySizeLabel;
    private JLabel ivSizeLabel;

    public void init(TabZuc parent) {
        macButton.setActionCommand("zucMac");
        macButton.addActionListener(parent.getAction());
        resetButton.setActionCommand("resetForm");
        resetButton.addActionListener(parent.getAction());
        generateKeyButton.setActionCommand("generateZucKey");
        generateKeyButton.addActionListener(parent.getAction());
        generateIvButton.setActionCommand("generateZucIv");
        generateIvButton.addActionListener(parent.getAction());

        // ZUC版本切换监听
        zuc128RadioButton.addActionListener(e -> {
            if (zuc128RadioButton.isSelected()) {
                keySizeLabel.setText("密钥(16字节)：");
                ivSizeLabel.setText("IV(16字节)：");
            }
        });
        zuc256RadioButton.addActionListener(e -> {
            if (zuc256RadioButton.isSelected()) {
                keySizeLabel.setText("密钥(32字节)：");
                ivSizeLabel.setText("IV(25字节)：");
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        zucMacPanel = new JPanel();
        zucMacPanel.setLayout(new GridLayoutManager(8, 4, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("ZUC版本：");
        zucMacPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        zuc128RadioButton = new JRadioButton();
        zuc128RadioButton.setSelected(true);
        zuc128RadioButton.setText("ZUC-128");
        zucMacPanel.add(zuc128RadioButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        zuc256RadioButton = new JRadioButton();
        zuc256RadioButton.setText("ZUC-256");
        zucMacPanel.add(zuc256RadioButton, new GridConstraints(0, 2, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        keySizeLabel = new JLabel();
        keySizeLabel.setText("密钥(16字节)：");
        zucMacPanel.add(keySizeLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        keyTextArea = new JTextArea();
        keyTextArea.setLineWrap(true);
        zucMacPanel.add(keyTextArea, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 50), null, 0, false));
        keyEncodeComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("HEX");
        defaultComboBoxModel1.addElement("BASE64");
        keyEncodeComboBox.setModel(defaultComboBoxModel1);
        zucMacPanel.add(keyEncodeComboBox, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        generateKeyButton = new JButton();
        generateKeyButton.setText("生成密钥");
        zucMacPanel.add(generateKeyButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ivSizeLabel = new JLabel();
        ivSizeLabel.setText("IV(16字节)：");
        zucMacPanel.add(ivSizeLabel, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ivTextArea = new JTextArea();
        ivTextArea.setLineWrap(true);
        zucMacPanel.add(ivTextArea, new GridConstraints(3, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 50), null, 0, false));
        ivEncodeComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        defaultComboBoxModel2.addElement("HEX");
        defaultComboBoxModel2.addElement("BASE64");
        ivEncodeComboBox.setModel(defaultComboBoxModel2);
        zucMacPanel.add(ivEncodeComboBox, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        generateIvButton = new JButton();
        generateIvButton.setText("生成IV");
        zucMacPanel.add(generateIvButton, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("输入数据：");
        zucMacPanel.add(label2, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        dataTextArea = new JTextArea();
        dataTextArea.setLineWrap(true);
        zucMacPanel.add(dataTextArea, new GridConstraints(5, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 50), null, 0, false));
        dataEncodeComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel3 = new DefaultComboBoxModel();
        defaultComboBoxModel3.addElement("UTF-8");
        defaultComboBoxModel3.addElement("HEX");
        defaultComboBoxModel3.addElement("BASE64");
        dataEncodeComboBox.setModel(defaultComboBoxModel3);
        zucMacPanel.add(dataEncodeComboBox, new GridConstraints(5, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("MAC输出：");
        zucMacPanel.add(label3, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        macTextArea = new JTextArea();
        macTextArea.setLineWrap(true);
        zucMacPanel.add(macTextArea, new GridConstraints(6, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 50), null, 0, false));
        macEncodeComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel4 = new DefaultComboBoxModel();
        defaultComboBoxModel4.addElement("HEX");
        defaultComboBoxModel4.addElement("BASE64");
        macEncodeComboBox.setModel(defaultComboBoxModel4);
        zucMacPanel.add(macEncodeComboBox, new GridConstraints(6, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        macButton = new JButton();
        macButton.setText("生成MAC");
        zucMacPanel.add(macButton, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        resetButton = new JButton();
        resetButton.setText("重置");
        zucMacPanel.add(resetButton, new GridConstraints(7, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return zucMacPanel;
    }

}
