package alg.bc.gui.view.viewInternational;

import alg.bc.gui.util.EncodeSwitchBinder;
import java.awt.event.ActionListener;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import lombok.Data;

import javax.swing.*;
import java.awt.*;

@Data
public class ViewIntCert {
    private JPanel certPanel;

    // 生成
    private JComboBox<Integer> genKeySizeComboBox;
    private JComboBox<String> genKeyEncodeComboBox;
    private JButton genKeyPairButton;
    private JTextField genSubjectTextField;
    private JTextField genDaysTextField;
    private JTextArea genPubKeyTextArea;
    private JTextArea genPrvKeyTextArea;
    private JButton genCsrButton;
    private JButton genSelfSignedButton;
    private JTextArea genResultTextArea;

    // 查看
    private JTextArea certInputTextArea;
    private JTextArea certInfoTextArea;
    private JTextArea trustPemTextArea;
    private JPasswordField p12PasswordField;
    private JButton parseButton;
    private JButton loadFileButton;
    private JButton resetButton;

    private JPanel toolPanel;
    private JButton toPemButton;
    private JButton toDerBase64Button;
    private JButton toDerHexButton;
    private JButton splitPemButton;
    private JButton verifyChainButton;
    private JButton saveInfoButton;
    private JButton buildChainButton;
    private JButton exportPemButton;
    private JButton exportDerButton;

    public void init(ActionListener action) {
        genKeyPairButton.setActionCommand("intRsaCertGenerateKeyPair");
        genKeyPairButton.addActionListener(action);
        genCsrButton.setActionCommand("intRsaCertGenerateCsr");
        genCsrButton.addActionListener(action);
        genSelfSignedButton.setActionCommand("intRsaCertGenerateSelfSigned");
        genSelfSignedButton.addActionListener(action);

        parseButton.setActionCommand("intRsaCertParse");
        parseButton.addActionListener(action);
        loadFileButton.setActionCommand("intRsaCertLoadFile");
        loadFileButton.addActionListener(action);
        resetButton.setActionCommand("intRsaCertReset");
        resetButton.addActionListener(action);

        toPemButton.setActionCommand("intRsaCertToPem");
        toPemButton.addActionListener(action);
        toDerBase64Button.setActionCommand("intRsaCertToDerBase64");
        toDerBase64Button.addActionListener(action);
        toDerHexButton.setActionCommand("intRsaCertToDerHex");
        toDerHexButton.addActionListener(action);
        splitPemButton.setActionCommand("intRsaCertSplitPem");
        splitPemButton.addActionListener(action);
        verifyChainButton.setActionCommand("intRsaCertVerifyChain");
        verifyChainButton.addActionListener(action);
        saveInfoButton.setActionCommand("intRsaCertSaveInfo");
        saveInfoButton.addActionListener(action);
        buildChainButton.setActionCommand("intRsaCertBuildChain");
        buildChainButton.addActionListener(action);
        exportPemButton.setActionCommand("intRsaCertExportPemFile");
        exportPemButton.addActionListener(action);
        exportDerButton.setActionCommand("intRsaCertExportDerFile");
        exportDerButton.addActionListener(action);

        EncodeSwitchBinder.bind(genKeyEncodeComboBox, genPubKeyTextArea, "公钥");
        EncodeSwitchBinder.bind(genKeyEncodeComboBox, genPrvKeyTextArea, "私钥");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        certPanel = new JPanel();
        certPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JTabbedPane tabbedPane1 = new JTabbedPane();
        certPanel.add(tabbedPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(7, 5, new Insets(10, 10, 10, 10), -1, -1));
        tabbedPane1.addTab("生成(RSA)", panel1);
        final JLabel label1 = new JLabel();
        label1.setText("KeySize：");
        panel1.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        genKeySizeComboBox = new JComboBox();
        panel1.add(genKeySizeComboBox, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        genKeyEncodeComboBox = new JComboBox();
        panel1.add(genKeyEncodeComboBox, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        genKeyPairButton = new JButton();
        genKeyPairButton.setText("生成RSA密钥对");
        panel1.add(genKeyPairButton, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Subject：");
        panel1.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        genSubjectTextField = new JTextField();
        panel1.add(genSubjectTextField, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("有效天数：");
        panel1.add(label3, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        genDaysTextField = new JTextField();
        panel1.add(genDaysTextField, new GridConstraints(1, 4, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("公钥(X.509)：");
        panel1.add(label4, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, new GridConstraints(2, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(500, 110), null, 0, false));
        genPubKeyTextArea = new JTextArea();
        genPubKeyTextArea.setLineWrap(true);
        genPubKeyTextArea.setRows(6);
        scrollPane1.setViewportView(genPubKeyTextArea);
        final JLabel label5 = new JLabel();
        label5.setText("私钥(PKCS#8)：");
        panel1.add(label5, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane2 = new JScrollPane();
        panel1.add(scrollPane2, new GridConstraints(3, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(500, 110), null, 0, false));
        genPrvKeyTextArea = new JTextArea();
        genPrvKeyTextArea.setLineWrap(true);
        genPrvKeyTextArea.setRows(6);
        scrollPane2.setViewportView(genPrvKeyTextArea);
        genCsrButton = new JButton();
        genCsrButton.setText("生成CSR");
        panel1.add(genCsrButton, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        genSelfSignedButton = new JButton();
        genSelfSignedButton.setText("生成自签证书");
        panel1.add(genSelfSignedButton, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label6 = new JLabel();
        label6.setText("输出(PEM/信息)：");
        panel1.add(label6, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane3 = new JScrollPane();
        panel1.add(scrollPane3, new GridConstraints(5, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(500, 160), null, 0, false));
        genResultTextArea = new JTextArea();
        genResultTextArea.setLineWrap(true);
        genResultTextArea.setRows(10);
        scrollPane3.setViewportView(genResultTextArea);
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(6, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(8, 3, new Insets(10, 10, 10, 10), -1, -1));
        tabbedPane1.addTab("查看", panel2);
        final JLabel label7 = new JLabel();
        label7.setText("证书/CSR/PKCS7/PKCS12：");
        panel2.add(label7, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane4 = new JScrollPane();
        panel2.add(scrollPane4, new GridConstraints(0, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(500, 150), null, 0, false));
        certInputTextArea = new JTextArea();
        certInputTextArea.setLineWrap(true);
        certInputTextArea.setRows(8);
        scrollPane4.setViewportView(certInputTextArea);
        parseButton = new JButton();
        parseButton.setText("解析");
        panel2.add(parseButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        loadFileButton = new JButton();
        loadFileButton.setText("加载文件");
        panel2.add(loadFileButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        resetButton = new JButton();
        resetButton.setText("重置");
        panel2.add(resetButton, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        toolPanel = new JPanel();
        panel2.add(toolPanel, new GridConstraints(2, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label8 = new JLabel();
        label8.setText("信任根/中间证书(PEM)：");
        panel2.add(label8, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane5 = new JScrollPane();
        panel2.add(scrollPane5, new GridConstraints(3, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(500, 110), null, 0, false));
        trustPemTextArea = new JTextArea();
        trustPemTextArea.setLineWrap(true);
        trustPemTextArea.setRows(5);
        scrollPane5.setViewportView(trustPemTextArea);
        final JLabel label9 = new JLabel();
        label9.setText("信息：");
        panel2.add(label9, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane6 = new JScrollPane();
        panel2.add(scrollPane6, new GridConstraints(4, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(500, 160), null, 0, false));
        certInfoTextArea = new JTextArea();
        certInfoTextArea.setLineWrap(true);
        certInfoTextArea.setRows(10);
        scrollPane6.setViewportView(certInfoTextArea);
        final Spacer spacer2 = new Spacer();
        panel2.add(spacer2, new GridConstraints(7, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return certPanel;
    }

}


