package alg.bc.gui.view.viewInternational;
import alg.bc.gui.util.EncodeSwitchBinder;
import java.awt.event.ActionListener;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import lombok.Data;

import javax.swing.*;
import java.awt.*;

@Data
public class ViewIntDes3 {
    private JPanel des3Panel;
    private JComboBox<Integer> keySizeComboBox;
    private JComboBox<String> modeComboBox;
    private JTextArea keyTextArea;
    private JComboBox<String> keyEncodeComboBox;
    private JButton generateKeyButton;
    private JTextArea ivTextArea;
    private JComboBox<String> ivEncodeComboBox;
    private JButton generateIvButton;
    private JTextArea inputTextArea;
    private JComboBox<String> inputEncodeComboBox;
    private JButton encryptButton;
    private JButton decryptButton;
    private JComboBox<String> outputEncodeComboBox;
    private JTextArea outputTextArea;

    public void init(ActionListener action) {
        ensureModels();
        generateKeyButton.setActionCommand("des3GenerateKey");
        generateKeyButton.addActionListener(action);
        generateIvButton.setActionCommand("des3GenerateIv");
        generateIvButton.addActionListener(action);
        encryptButton.setActionCommand("des3Encrypt");
        encryptButton.addActionListener(action);
        decryptButton.setActionCommand("des3Decrypt");
        decryptButton.addActionListener(action);

        EncodeSwitchBinder.bind(keyEncodeComboBox, keyTextArea, "密钥");
        EncodeSwitchBinder.bind(ivEncodeComboBox, ivTextArea, "IV");
        EncodeSwitchBinder.bind(inputEncodeComboBox, inputTextArea, "输入");
        EncodeSwitchBinder.bind(outputEncodeComboBox, outputTextArea, "输出");
    }

    @SuppressWarnings({"rawtypes", "unchecked"})
    private void ensureModels() {
        if (keySizeComboBox != null && keySizeComboBox.getItemCount() == 0) {
            keySizeComboBox.setModel(new DefaultComboBoxModel(new Integer[]{112, 128, 168, 192}));
        }
        if (modeComboBox != null && modeComboBox.getItemCount() == 0) {
            modeComboBox.setModel(new DefaultComboBoxModel(new String[]{"ECB", "CBC"}));
        }
        if (keyEncodeComboBox != null && keyEncodeComboBox.getItemCount() == 0) {
            keyEncodeComboBox.setModel(new DefaultComboBoxModel(new String[]{"HEX", "BASE64"}));
        }
        if (ivEncodeComboBox != null && ivEncodeComboBox.getItemCount() == 0) {
            ivEncodeComboBox.setModel(new DefaultComboBoxModel(new String[]{"HEX", "BASE64"}));
        }
        if (inputEncodeComboBox != null && inputEncodeComboBox.getItemCount() == 0) {
            inputEncodeComboBox.setModel(new DefaultComboBoxModel(new String[]{"UTF-8", "HEX", "BASE64"}));
        }
        if (outputEncodeComboBox != null && outputEncodeComboBox.getItemCount() == 0) {
            outputEncodeComboBox.setModel(new DefaultComboBoxModel(new String[]{"HEX", "BASE64", "UTF-8"}));
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        des3Panel = new JPanel();
        des3Panel.setLayout(new GridLayoutManager(9, 4, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("KeySize：");
        des3Panel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        keySizeComboBox = new JComboBox();
        des3Panel.add(keySizeComboBox, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Mode：");
        des3Panel.add(label2, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        modeComboBox = new JComboBox();
        des3Panel.add(modeComboBox, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("密钥：");
        des3Panel.add(label3, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        des3Panel.add(scrollPane1, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 70), null, 0, false));
        keyTextArea = new JTextArea();
        keyTextArea.setLineWrap(true);
        keyTextArea.setRows(4);
        scrollPane1.setViewportView(keyTextArea);
        keyEncodeComboBox = new JComboBox();
        des3Panel.add(keyEncodeComboBox, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        generateKeyButton = new JButton();
        generateKeyButton.setText("生成密钥");
        des3Panel.add(generateKeyButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("IV(CBC)：");
        des3Panel.add(label4, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane2 = new JScrollPane();
        des3Panel.add(scrollPane2, new GridConstraints(3, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 55), null, 0, false));
        ivTextArea = new JTextArea();
        ivTextArea.setLineWrap(true);
        ivTextArea.setRows(3);
        scrollPane2.setViewportView(ivTextArea);
        ivEncodeComboBox = new JComboBox();
        des3Panel.add(ivEncodeComboBox, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        generateIvButton = new JButton();
        generateIvButton.setText("生成IV(8B)");
        des3Panel.add(generateIvButton, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("输入：");
        des3Panel.add(label5, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane3 = new JScrollPane();
        des3Panel.add(scrollPane3, new GridConstraints(5, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 110), null, 0, false));
        inputTextArea = new JTextArea();
        inputTextArea.setLineWrap(true);
        inputTextArea.setRows(6);
        scrollPane3.setViewportView(inputTextArea);
        inputEncodeComboBox = new JComboBox();
        des3Panel.add(inputEncodeComboBox, new GridConstraints(5, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        encryptButton = new JButton();
        encryptButton.setText("加密");
        des3Panel.add(encryptButton, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        decryptButton = new JButton();
        decryptButton.setText("解密");
        des3Panel.add(decryptButton, new GridConstraints(6, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        outputEncodeComboBox = new JComboBox();
        des3Panel.add(outputEncodeComboBox, new GridConstraints(6, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label6 = new JLabel();
        label6.setText("输出：");
        des3Panel.add(label6, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane4 = new JScrollPane();
        des3Panel.add(scrollPane4, new GridConstraints(7, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 110), null, 0, false));
        outputTextArea = new JTextArea();
        outputTextArea.setLineWrap(true);
        outputTextArea.setRows(6);
        scrollPane4.setViewportView(outputTextArea);
        final Spacer spacer1 = new Spacer();
        des3Panel.add(spacer1, new GridConstraints(8, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return des3Panel;
    }

}


