package alg.bc.gui.view.viewInternational;

import alg.bc.gui.util.EncodeSwitchBinder;
import java.awt.event.ActionListener;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import lombok.Data;

import javax.swing.*;
import java.awt.*;

@Data
public class ViewIntRsa {
    private JPanel rsaPanel;

    // KeyPair tab
    private JComboBox<Integer> keySizeComboBox;
    private JComboBox<String> keyEncodeComboBox;
    private JButton generateKeyPairButton;
    private JTextArea pubKeyTextArea;
    private JTextArea prvKeyTextArea;

    // Cipher tab
    private JComboBox<String> encryptKeyTypeComboBox;
    private JTextArea encryptKeyTextArea;
    private JComboBox<String> decryptKeyTypeComboBox;
    private JTextArea decryptKeyTextArea;
    private JTextArea cipherInputTextArea;
    private JComboBox<String> cipherInputEncodeComboBox;
    private JButton rsaEncryptButton;
    private JButton rsaDecryptButton;
    private JComboBox<String> cipherOutputEncodeComboBox;
    private JTextArea cipherOutputTextArea;

    // Sign/Verify tab
    private JTextArea signPrvKeyTextArea;
    private JTextArea signMsgTextArea;
    private JComboBox<String> signMsgEncodeComboBox;
    private JButton signButton;
    private JTextArea signOutTextArea;
    private JComboBox<String> signOutEncodeComboBox;

    private JTextArea verifyPubKeyTextArea;
    private JTextArea verifyMsgTextArea;
    private JComboBox<String> verifyMsgEncodeComboBox;
    private JTextArea verifySigTextArea;
    private JComboBox<String> verifySigEncodeComboBox;
    private JButton verifyButton;

    public void init(ActionListener action) {
        generateKeyPairButton.setActionCommand("rsaGenerateKeyPair");
        generateKeyPairButton.addActionListener(action);

        rsaEncryptButton.setActionCommand("rsaEncrypt");
        rsaEncryptButton.addActionListener(action);
        rsaDecryptButton.setActionCommand("rsaDecrypt");
        rsaDecryptButton.addActionListener(action);

        signButton.setActionCommand("rsaSign");
        signButton.addActionListener(action);
        verifyButton.setActionCommand("rsaVerify");
        verifyButton.addActionListener(action);

        // 编码切换
        EncodeSwitchBinder.bind(keyEncodeComboBox, pubKeyTextArea, "公钥");
        EncodeSwitchBinder.bind(keyEncodeComboBox, prvKeyTextArea, "私钥");
        EncodeSwitchBinder.bind(cipherInputEncodeComboBox, cipherInputTextArea, "数据");
        EncodeSwitchBinder.bind(cipherOutputEncodeComboBox, cipherOutputTextArea, "输出");
        EncodeSwitchBinder.bind(signMsgEncodeComboBox, signMsgTextArea, "待签名数据");
        EncodeSwitchBinder.bind(signOutEncodeComboBox, signOutTextArea, "签名值");
        EncodeSwitchBinder.bind(verifyMsgEncodeComboBox, verifyMsgTextArea, "待验签数据");
        EncodeSwitchBinder.bind(verifySigEncodeComboBox, verifySigTextArea, "签名值");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rsaPanel = new JPanel();
        rsaPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JTabbedPane tabbedPane1 = new JTabbedPane();
        rsaPanel.add(tabbedPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(4, 4, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("密钥对", panel1);
        final JLabel label1 = new JLabel();
        label1.setText("KeySize：");
        panel1.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        keySizeComboBox = new JComboBox();
        panel1.add(keySizeComboBox, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        keyEncodeComboBox = new JComboBox();
        panel1.add(keyEncodeComboBox, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        generateKeyPairButton = new JButton();
        generateKeyPairButton.setText("生成密钥对");
        panel1.add(generateKeyPairButton, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("公钥(X.509)：");
        panel1.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, new GridConstraints(1, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(500, 110), null, 0, false));
        pubKeyTextArea = new JTextArea();
        pubKeyTextArea.setLineWrap(true);
        pubKeyTextArea.setRows(6);
        scrollPane1.setViewportView(pubKeyTextArea);
        final JLabel label3 = new JLabel();
        label3.setText("私钥(PKCS#8)：");
        panel1.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane2 = new JScrollPane();
        panel1.add(scrollPane2, new GridConstraints(2, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(500, 110), null, 0, false));
        prvKeyTextArea = new JTextArea();
        prvKeyTextArea.setLineWrap(true);
        prvKeyTextArea.setRows(6);
        scrollPane2.setViewportView(prvKeyTextArea);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(6, 4, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("加解密", panel2);
        final JLabel label4 = new JLabel();
        label4.setText("加密密钥：");
        panel2.add(label4, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane3 = new JScrollPane();
        panel2.add(scrollPane3, new GridConstraints(0, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(500, 70), null, 0, false));
        encryptKeyTextArea = new JTextArea();
        encryptKeyTextArea.setLineWrap(true);
        encryptKeyTextArea.setRows(4);
        scrollPane3.setViewportView(encryptKeyTextArea);
        encryptKeyTypeComboBox = new JComboBox();
        panel2.add(encryptKeyTypeComboBox, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("解密密钥：");
        panel2.add(label5, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane4 = new JScrollPane();
        panel2.add(scrollPane4, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(500, 70), null, 0, false));
        decryptKeyTextArea = new JTextArea();
        decryptKeyTextArea.setLineWrap(true);
        decryptKeyTextArea.setRows(4);
        scrollPane4.setViewportView(decryptKeyTextArea);
        decryptKeyTypeComboBox = new JComboBox();
        panel2.add(decryptKeyTypeComboBox, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label6 = new JLabel();
        label6.setText("输入：");
        panel2.add(label6, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane5 = new JScrollPane();
        panel2.add(scrollPane5, new GridConstraints(2, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(500, 110), null, 0, false));
        cipherInputTextArea = new JTextArea();
        cipherInputTextArea.setLineWrap(true);
        cipherInputTextArea.setRows(6);
        scrollPane5.setViewportView(cipherInputTextArea);
        cipherInputEncodeComboBox = new JComboBox();
        panel2.add(cipherInputEncodeComboBox, new GridConstraints(2, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rsaEncryptButton = new JButton();
        rsaEncryptButton.setText("加密");
        panel2.add(rsaEncryptButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rsaDecryptButton = new JButton();
        rsaDecryptButton.setText("解密");
        panel2.add(rsaDecryptButton, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cipherOutputEncodeComboBox = new JComboBox();
        panel2.add(cipherOutputEncodeComboBox, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label7 = new JLabel();
        label7.setText("输出：");
        panel2.add(label7, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane6 = new JScrollPane();
        panel2.add(scrollPane6, new GridConstraints(4, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(500, 110), null, 0, false));
        cipherOutputTextArea = new JTextArea();
        cipherOutputTextArea.setLineWrap(true);
        cipherOutputTextArea.setRows(6);
        scrollPane6.setViewportView(cipherOutputTextArea);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(8, 3, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("签名验签", panel3);
        final JLabel label8 = new JLabel();
        label8.setText("签名私钥：");
        panel3.add(label8, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane7 = new JScrollPane();
        panel3.add(scrollPane7, new GridConstraints(0, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(500, 70), null, 0, false));
        signPrvKeyTextArea = new JTextArea();
        signPrvKeyTextArea.setLineWrap(true);
        signPrvKeyTextArea.setRows(4);
        scrollPane7.setViewportView(signPrvKeyTextArea);
        final JLabel label9 = new JLabel();
        label9.setText("签名数据：");
        panel3.add(label9, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane8 = new JScrollPane();
        panel3.add(scrollPane8, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 110), null, 0, false));
        signMsgTextArea = new JTextArea();
        signMsgTextArea.setLineWrap(true);
        signMsgTextArea.setRows(6);
        scrollPane8.setViewportView(signMsgTextArea);
        signMsgEncodeComboBox = new JComboBox();
        panel3.add(signMsgEncodeComboBox, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        signButton = new JButton();
        signButton.setText("签名(SHA256withRSA)");
        panel3.add(signButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label10 = new JLabel();
        label10.setText("签名值：");
        panel3.add(label10, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane9 = new JScrollPane();
        panel3.add(scrollPane9, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 70), null, 0, false));
        signOutTextArea = new JTextArea();
        signOutTextArea.setLineWrap(true);
        signOutTextArea.setRows(4);
        scrollPane9.setViewportView(signOutTextArea);
        signOutEncodeComboBox = new JComboBox();
        panel3.add(signOutEncodeComboBox, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label11 = new JLabel();
        label11.setText("验签公钥：");
        panel3.add(label11, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane10 = new JScrollPane();
        panel3.add(scrollPane10, new GridConstraints(4, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(500, 70), null, 0, false));
        verifyPubKeyTextArea = new JTextArea();
        verifyPubKeyTextArea.setLineWrap(true);
        verifyPubKeyTextArea.setRows(4);
        scrollPane10.setViewportView(verifyPubKeyTextArea);
        final JLabel label12 = new JLabel();
        label12.setText("验签数据：");
        panel3.add(label12, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane11 = new JScrollPane();
        panel3.add(scrollPane11, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 110), null, 0, false));
        verifyMsgTextArea = new JTextArea();
        verifyMsgTextArea.setLineWrap(true);
        verifyMsgTextArea.setRows(6);
        scrollPane11.setViewportView(verifyMsgTextArea);
        verifyMsgEncodeComboBox = new JComboBox();
        panel3.add(verifyMsgEncodeComboBox, new GridConstraints(5, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label13 = new JLabel();
        label13.setText("验签签名：");
        panel3.add(label13, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane12 = new JScrollPane();
        panel3.add(scrollPane12, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 70), null, 0, false));
        verifySigTextArea = new JTextArea();
        verifySigTextArea.setLineWrap(true);
        verifySigTextArea.setRows(4);
        scrollPane12.setViewportView(verifySigTextArea);
        verifySigEncodeComboBox = new JComboBox();
        panel3.add(verifySigEncodeComboBox, new GridConstraints(6, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        verifyButton = new JButton();
        verifyButton.setText("验签");
        panel3.add(verifyButton, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rsaPanel;
    }

}


