package alg.bc.gui.view.viewInternational;

import alg.bc.gui.util.EncodeSwitchBinder;
import java.awt.event.ActionListener;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import lombok.Data;

import javax.swing.*;
import java.awt.*;

@Data
public class ViewIntMac {
    private JPanel macPanel;
    private JComboBox<String> algComboBox;
    private JButton macButton;
    private JTextArea msgTextArea;
    private JComboBox<String> msgEncodeComboBox;
    private JTextArea keyTextArea;
    private JComboBox<String> keyEncodeComboBox;
    private JTextArea outTextArea;
    private JComboBox<String> outEncodeComboBox;

    public void init(ActionListener action) {
        ensureModels();
        macButton.setActionCommand("macDo");
        macButton.addActionListener(action);
        EncodeSwitchBinder.bind(msgEncodeComboBox, msgTextArea, "消息");
        EncodeSwitchBinder.bind(keyEncodeComboBox, keyTextArea, "密钥");
        EncodeSwitchBinder.bind(outEncodeComboBox, outTextArea, "输出");
    }

    @SuppressWarnings({"rawtypes", "unchecked"})
    private void ensureModels() {
        if (algComboBox != null && algComboBox.getItemCount() == 0) {
            algComboBox.setModel(new DefaultComboBoxModel(new String[]{"HMAC-MD5", "HMAC-SHA256", "AES-CMAC", "DES-CMAC"}));
        }
        if (msgEncodeComboBox != null && msgEncodeComboBox.getItemCount() == 0) {
            msgEncodeComboBox.setModel(new DefaultComboBoxModel(new String[]{"UTF-8", "HEX", "BASE64"}));
        }
        if (keyEncodeComboBox != null && keyEncodeComboBox.getItemCount() == 0) {
            keyEncodeComboBox.setModel(new DefaultComboBoxModel(new String[]{"HEX", "BASE64"}));
        }
        if (outEncodeComboBox != null && outEncodeComboBox.getItemCount() == 0) {
            outEncodeComboBox.setModel(new DefaultComboBoxModel(new String[]{"HEX", "BASE64"}));
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        macPanel = new JPanel();
        macPanel.setLayout(new GridLayoutManager(7, 3, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("算法：");
        macPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        algComboBox = new JComboBox();
        macPanel.add(algComboBox, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        macButton = new JButton();
        macButton.setText("计算MAC");
        macPanel.add(macButton, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("消息：");
        macPanel.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        macPanel.add(scrollPane1, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 140), null, 0, false));
        msgTextArea = new JTextArea();
        msgTextArea.setLineWrap(true);
        msgTextArea.setRows(8);
        scrollPane1.setViewportView(msgTextArea);
        msgEncodeComboBox = new JComboBox();
        macPanel.add(msgEncodeComboBox, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("密钥：");
        macPanel.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane2 = new JScrollPane();
        macPanel.add(scrollPane2, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 90), null, 0, false));
        keyTextArea = new JTextArea();
        keyTextArea.setLineWrap(true);
        keyTextArea.setRows(4);
        scrollPane2.setViewportView(keyTextArea);
        keyEncodeComboBox = new JComboBox();
        macPanel.add(keyEncodeComboBox, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("输出：");
        macPanel.add(label4, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane3 = new JScrollPane();
        macPanel.add(scrollPane3, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 90), null, 0, false));
        outTextArea = new JTextArea();
        outTextArea.setLineWrap(true);
        outTextArea.setRows(4);
        scrollPane3.setViewportView(outTextArea);
        outEncodeComboBox = new JComboBox();
        macPanel.add(outEncodeComboBox, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        macPanel.add(spacer1, new GridConstraints(6, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return macPanel;
    }

}


