package alg.bc.gui.view;

import alg.bc.gui.action.ActionSm9;
import alg.bc.gui.view.viewSm9.ViewSm9Cipher;
import alg.bc.gui.view.viewSm9.ViewSm9Kgc;
import alg.bc.gui.view.viewSm9.ViewSm9Sign;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import lombok.Data;

import javax.swing.*;
import java.awt.*;

@Data
public class TabSm9 {

    private JPanel sm9Panel;
    private ViewSm9Kgc kgcView;
    private ViewSm9Cipher cipherView;
    private ViewSm9Sign signView;

    private ActionSm9 action;

    public TabSm9() {
        action = new ActionSm9(this);
        // Initialize UI and Sub-views
        $$$setupUI$$$();

        // Bind actions safely after 'action' is created
        if (kgcView != null)
            kgcView.init(this);
        if (cipherView != null)
            cipherView.init(this);
        if (signView != null)
            signView.init(this);
    }

    // Delegation Getters for ActionSm9 Compatibility

    // KGC View fields
    public JComboBox<String> getKeyEncodeComboBox() {
        return kgcView.getKeyEncodeComboBox();
    }

    public JTextField getKgcUserIdTextField() {
        return kgcView.getKgcUserIdTextField();
    }

    public JButton getGenEncMasterButton() {
        return kgcView.getGenEncMasterButton();
    }

    public JButton getGenSignMasterButton() {
        return kgcView.getGenSignMasterButton();
    }

    public JButton getDeriveEncSkButton() {
        return kgcView.getDeriveEncSkButton();
    }

    public JButton getDeriveSignSkButton() {
        return kgcView.getDeriveSignSkButton();
    }

    public JTextArea getMskEncTextArea() {
        return kgcView.getMskEncTextArea();
    }

    public JTextArea getMpkEncTextArea() {
        return kgcView.getMpkEncTextArea();
    }

    public JTextArea getSkEncTextArea() {
        return kgcView.getSkEncTextArea();
    }

    public JTextArea getMskSignTextArea() {
        return kgcView.getMskSignTextArea();
    }

    public JTextArea getMpkSignTextArea() {
        return kgcView.getMpkSignTextArea();
    }

    public JTextArea getSkSignTextArea() {
        return kgcView.getSkSignTextArea();
    }

    // Cipher View fields
    public JTextField getCipherUserIdTextField() {
        return cipherView.getCipherUserIdTextField();
    }

    public JTextArea getEncryptMpkEncTextArea() {
        return cipherView.getEncryptMpkEncTextArea();
    }

    public JTextArea getDecryptSkEncTextArea() {
        return cipherView.getDecryptSkEncTextArea();
    }

    public JComboBox<String> getPlainEncodeComboBox() {
        return cipherView.getPlainEncodeComboBox();
    }

    public JTextArea getPlainTextArea() {
        return cipherView.getPlainTextArea();
    }

    public JComboBox<String> getCipherEncodeComboBox() {
        return cipherView.getCipherEncodeComboBox();
    }

    public JTextArea getCipherTextArea() {
        return cipherView.getCipherTextArea();
    }

    public JButton getEncryptButton() {
        return cipherView.getEncryptButton();
    }

    public JButton getDecryptButton() {
        return cipherView.getDecryptButton();
    }

    // Sign View fields
    public JTextField getSignUserIdTextField() {
        return signView.getSignUserIdTextField();
    }

    public JTextArea getSignSkSignTextArea() {
        return signView.getSignSkSignTextArea();
    }

    public JTextArea getVerifyMpkSignTextArea() {
        return signView.getVerifyMpkSignTextArea();
    }

    public JComboBox<String> getMsgEncodeComboBox() {
        return signView.getMsgEncodeComboBox();
    }

    public JTextArea getMsgTextArea() {
        return signView.getMsgTextArea();
    }

    public JComboBox<String> getSigEncodeComboBox() {
        return signView.getSigEncodeComboBox();
    }

    public JTextArea getSigTextArea() {
        return signView.getSigTextArea();
    }

    public JButton getSignButton() {
        return signView.getSignButton();
    }

    public JButton getVerifyButton() {
        return signView.getVerifyButton();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        sm9Panel = new JPanel();
        sm9Panel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JTabbedPane tabbedPane1 = new JTabbedPane();
        sm9Panel.add(tabbedPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1, true, true));
        tabbedPane1.addTab("KGC/派生", panel1);
        kgcView = new ViewSm9Kgc();
        panel1.add(kgcView.$$$getRootComponent$$$(), new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1, true, true));
        tabbedPane1.addTab("加解密", panel2);
        cipherView = new ViewSm9Cipher();
        panel2.add(cipherView.$$$getRootComponent$$$(), new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("签名验签", panel3);
        signView = new ViewSm9Sign();
        panel3.add(signView.$$$getRootComponent$$$(), new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return sm9Panel;
    }
}
