package alg.bc.gui.view.viewSm4;

import alg.bc.gui.view.TabSm4;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import lombok.Data;

import javax.swing.*;
import java.awt.*;

@Data
public class ViewSm4Encrypt {
    private JPanel sm4EncryptPanel;
    private JTextArea keyTextArea;
    private JComboBox<String> keyEncodeComboBox;
    private JTextArea dataTextArea;
    private JComboBox<String> dataEncodeComboBox;
    private JComboBox<String> modeComboBox;
    private JComboBox<String> paddingComboBox;
    private JTextArea ivTextArea;
    private JComboBox<String> ivEncodeComboBox;
    private JTextArea cipherTextArea;
    private JComboBox<String> cipherEncodeComboBox;
    private JButton encryptButton;
    private JButton resetButton;
    private JButton generateKeyButton;
    private JButton generateIvButton;
    private JLabel ivLabel;

    public void init(TabSm4 parent) {
        encryptButton.setActionCommand("sm4Encrypt");
        encryptButton.addActionListener(parent.getAction());
        resetButton.setActionCommand("resetForm");
        resetButton.addActionListener(parent.getAction());
        generateKeyButton.setActionCommand("generateSm4Key");
        generateKeyButton.addActionListener(parent.getAction());
        generateIvButton.setActionCommand("generateSm4Iv");
        generateIvButton.addActionListener(parent.getAction());

        // 模式切换监听（某些模式不需要IV）
        modeComboBox.addActionListener(e -> {
            String mode = modeComboBox.getSelectedItem().toString();
            boolean needsIv = !mode.equals("ECB");
            ivLabel.setVisible(needsIv);
            ivTextArea.setVisible(needsIv);
            ivEncodeComboBox.setVisible(needsIv);
            generateIvButton.setVisible(needsIv);
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        sm4EncryptPanel = new JPanel();
        sm4EncryptPanel.setLayout(new GridLayoutManager(8, 4, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("密钥：");
        sm4EncryptPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        keyTextArea = new JTextArea();
        keyTextArea.setLineWrap(true);
        sm4EncryptPanel.add(keyTextArea, new GridConstraints(0, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 50), null, 0, false));
        keyEncodeComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("HEX");
        defaultComboBoxModel1.addElement("BASE64");
        keyEncodeComboBox.setModel(defaultComboBoxModel1);
        sm4EncryptPanel.add(keyEncodeComboBox, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        generateKeyButton = new JButton();
        generateKeyButton.setText("生成密钥");
        sm4EncryptPanel.add(generateKeyButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("明文：");
        sm4EncryptPanel.add(label2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        dataTextArea = new JTextArea();
        dataTextArea.setLineWrap(true);
        sm4EncryptPanel.add(dataTextArea, new GridConstraints(2, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 50), null, 0, false));
        dataEncodeComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        defaultComboBoxModel2.addElement("UTF-8");
        defaultComboBoxModel2.addElement("HEX");
        defaultComboBoxModel2.addElement("BASE64");
        dataEncodeComboBox.setModel(defaultComboBoxModel2);
        sm4EncryptPanel.add(dataEncodeComboBox, new GridConstraints(2, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("模式：");
        sm4EncryptPanel.add(label3, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        modeComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel3 = new DefaultComboBoxModel();
        defaultComboBoxModel3.addElement("ECB");
        defaultComboBoxModel3.addElement("CBC");
        defaultComboBoxModel3.addElement("CFB");
        defaultComboBoxModel3.addElement("OFB");
        defaultComboBoxModel3.addElement("GCM");
        modeComboBox.setModel(defaultComboBoxModel3);
        sm4EncryptPanel.add(modeComboBox, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("填充：");
        sm4EncryptPanel.add(label4, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        paddingComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel4 = new DefaultComboBoxModel();
        defaultComboBoxModel4.addElement("PKCS7");
        defaultComboBoxModel4.addElement("NoPadding");
        paddingComboBox.setModel(defaultComboBoxModel4);
        sm4EncryptPanel.add(paddingComboBox, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ivLabel = new JLabel();
        ivLabel.setText("IV：");
        sm4EncryptPanel.add(ivLabel, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ivTextArea = new JTextArea();
        ivTextArea.setLineWrap(true);
        sm4EncryptPanel.add(ivTextArea, new GridConstraints(4, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 50), null, 0, false));
        ivEncodeComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel5 = new DefaultComboBoxModel();
        defaultComboBoxModel5.addElement("HEX");
        defaultComboBoxModel5.addElement("BASE64");
        ivEncodeComboBox.setModel(defaultComboBoxModel5);
        sm4EncryptPanel.add(ivEncodeComboBox, new GridConstraints(4, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        generateIvButton = new JButton();
        generateIvButton.setText("生成IV");
        sm4EncryptPanel.add(generateIvButton, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("密文：");
        sm4EncryptPanel.add(label5, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cipherTextArea = new JTextArea();
        cipherTextArea.setLineWrap(true);
        sm4EncryptPanel.add(cipherTextArea, new GridConstraints(6, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 50), null, 0, false));
        cipherEncodeComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel6 = new DefaultComboBoxModel();
        defaultComboBoxModel6.addElement("HEX");
        defaultComboBoxModel6.addElement("BASE64");
        cipherEncodeComboBox.setModel(defaultComboBoxModel6);
        sm4EncryptPanel.add(cipherEncodeComboBox, new GridConstraints(6, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        encryptButton = new JButton();
        encryptButton.setText("加密");
        sm4EncryptPanel.add(encryptButton, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        resetButton = new JButton();
        resetButton.setText("重置");
        sm4EncryptPanel.add(resetButton, new GridConstraints(7, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return sm4EncryptPanel;
    }

}
