package alg.bc.gui.view.viewSm9;

import alg.bc.gui.view.TabSm9;
import alg.bc.gui.util.EncodeSwitchBinder;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import lombok.Data;

import javax.swing.*;
import java.awt.*;

@Data
public class ViewSm9Sign {
    private JPanel panel;
    private JTextField signUserIdTextField;
    private JTextArea signSkSignTextArea;
    private JTextArea verifyMpkSignTextArea;
    private JComboBox<String> msgEncodeComboBox;
    private JTextArea msgTextArea;
    private JComboBox<String> sigEncodeComboBox;
    private JTextArea sigTextArea;
    private JButton signButton;
    private JButton verifyButton;

    public void init(TabSm9 parent) {
        // Actions
        signButton.setActionCommand("sm9Sign");
        signButton.addActionListener(parent.getAction());
        verifyButton.setActionCommand("sm9Verify");
        verifyButton.addActionListener(parent.getAction());

        // Binders
        JComboBox<String> keyEncode = parent.getKgcView().getKeyEncodeComboBox();
        EncodeSwitchBinder.bind(keyEncode, signSkSignTextArea, "skSign");
        EncodeSwitchBinder.bind(keyEncode, verifyMpkSignTextArea, "mpkSign");

        EncodeSwitchBinder.bind(msgEncodeComboBox, msgTextArea, "消息");
        EncodeSwitchBinder.bind(sigEncodeComboBox, sigTextArea, "签名值");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(7, 4, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("签名者ID：");
        panel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        signUserIdTextField = new JTextField();
        signUserIdTextField.setText("signer@example.com");
        panel.add(signUserIdTextField, new GridConstraints(0, 1, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("用户私钥(sk)：");
        panel.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel.add(scrollPane1, new GridConstraints(1, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        signSkSignTextArea = new JTextArea();
        signSkSignTextArea.setLineWrap(true);
        signSkSignTextArea.setRows(4);
        scrollPane1.setViewportView(signSkSignTextArea);
        final JLabel label3 = new JLabel();
        label3.setText("签名主公钥(mpk)：");
        panel.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane2 = new JScrollPane();
        panel.add(scrollPane2, new GridConstraints(2, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        verifyMpkSignTextArea = new JTextArea();
        verifyMpkSignTextArea.setLineWrap(true);
        verifyMpkSignTextArea.setRows(4);
        scrollPane2.setViewportView(verifyMpkSignTextArea);
        final JLabel label4 = new JLabel();
        label4.setText("消息：");
        panel.add(label4, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane3 = new JScrollPane();
        panel.add(scrollPane3, new GridConstraints(3, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        msgTextArea = new JTextArea();
        msgTextArea.setLineWrap(true);
        msgTextArea.setRows(6);
        scrollPane3.setViewportView(msgTextArea);
        msgEncodeComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("UTF-8");
        defaultComboBoxModel1.addElement("HEX");
        defaultComboBoxModel1.addElement("BASE64");
        msgEncodeComboBox.setModel(defaultComboBoxModel1);
        panel.add(msgEncodeComboBox, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 12, 0));
        panel.add(panel1, new GridConstraints(4, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        signButton = new JButton();
        signButton.setText("签名");
        panel1.add(signButton);
        verifyButton = new JButton();
        verifyButton.setText("验签");
        panel1.add(verifyButton);
        final JLabel label5 = new JLabel();
        label5.setText("签名值：");
        panel.add(label5, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane4 = new JScrollPane();
        panel.add(scrollPane4, new GridConstraints(5, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        sigTextArea = new JTextArea();
        sigTextArea.setLineWrap(true);
        sigTextArea.setRows(5);
        scrollPane4.setViewportView(sigTextArea);
        sigEncodeComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        defaultComboBoxModel2.addElement("HEX");
        defaultComboBoxModel2.addElement("BASE64");
        sigEncodeComboBox.setModel(defaultComboBoxModel2);
        panel.add(sigEncodeComboBox, new GridConstraints(5, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel.add(spacer1, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

    private JTextArea area(int rows) {
        JTextArea t = new JTextArea();
        t.setRows(rows);
        t.setLineWrap(true);
        return t;
    }

    private JScrollPane scroll(JTextArea t) {
        return new JScrollPane(t);
    }

    // Fixed add method
    private void add(JPanel p, Component comp, GridBagConstraints c, int x, int y, int w, double wx) {
        GridBagConstraints curr = (GridBagConstraints) c.clone();
        curr.gridx = x;
        curr.gridy = y;
        curr.gridwidth = w;
        curr.weightx = wx;
        if (comp instanceof JScrollPane) {
            curr.fill = GridBagConstraints.BOTH;
            curr.weighty = 1.0;
        }
        p.add(comp, curr);
    }

}
