package alg.bc.gui.view.viewSm9;

import alg.bc.gui.view.TabSm9;
import alg.bc.gui.util.EncodeSwitchBinder;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import lombok.Data;

import javax.swing.*;
import java.awt.*;

@Data
public class ViewSm9Cipher {
    private JPanel panel;
    private JTextField cipherUserIdTextField;
    private JTextArea encryptMpkEncTextArea;
    private JTextArea decryptSkEncTextArea;
    private JComboBox<String> plainEncodeComboBox;
    private JTextArea plainTextArea;
    private JComboBox<String> cipherEncodeComboBox;
    private JTextArea cipherTextArea;
    private JButton encryptButton;
    private JButton decryptButton;

    public void init(TabSm9 parent) {
        // Actions
        encryptButton.setActionCommand("sm9Encrypt");
        encryptButton.addActionListener(parent.getAction());
        decryptButton.setActionCommand("sm9Decrypt");
        decryptButton.addActionListener(parent.getAction());

        // Binders
        // Key encoding comes from KGC view (shared control)
        JComboBox<String> keyEncode = parent.getKgcView().getKeyEncodeComboBox();
        EncodeSwitchBinder.bind(keyEncode, encryptMpkEncTextArea, "mpkEnc");
        EncodeSwitchBinder.bind(keyEncode, decryptSkEncTextArea, "skEnc");

        EncodeSwitchBinder.bind(plainEncodeComboBox, plainTextArea, "明文/明文输出");
        EncodeSwitchBinder.bind(cipherEncodeComboBox, cipherTextArea, "密文");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(7, 4, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("接收方ID：");
        panel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cipherUserIdTextField = new JTextField();
        cipherUserIdTextField.setText("receiver@example.com");
        panel.add(cipherUserIdTextField, new GridConstraints(0, 1, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("加密主公钥(mpk)：");
        panel.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel.add(scrollPane1, new GridConstraints(1, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        encryptMpkEncTextArea = new JTextArea();
        encryptMpkEncTextArea.setLineWrap(true);
        encryptMpkEncTextArea.setRows(4);
        scrollPane1.setViewportView(encryptMpkEncTextArea);
        final JLabel label3 = new JLabel();
        label3.setText("用户私钥(sk)：");
        panel.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane2 = new JScrollPane();
        panel.add(scrollPane2, new GridConstraints(2, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        decryptSkEncTextArea = new JTextArea();
        decryptSkEncTextArea.setLineWrap(true);
        decryptSkEncTextArea.setRows(4);
        scrollPane2.setViewportView(decryptSkEncTextArea);
        final JLabel label4 = new JLabel();
        label4.setText("明文：");
        panel.add(label4, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane3 = new JScrollPane();
        panel.add(scrollPane3, new GridConstraints(3, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        plainTextArea = new JTextArea();
        plainTextArea.setLineWrap(true);
        plainTextArea.setRows(6);
        scrollPane3.setViewportView(plainTextArea);
        plainEncodeComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("UTF-8");
        defaultComboBoxModel1.addElement("HEX");
        defaultComboBoxModel1.addElement("BASE64");
        plainEncodeComboBox.setModel(defaultComboBoxModel1);
        panel.add(plainEncodeComboBox, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 12, 0));
        panel.add(panel1, new GridConstraints(4, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        encryptButton = new JButton();
        encryptButton.setText("加密 ->");
        panel1.add(encryptButton);
        decryptButton = new JButton();
        decryptButton.setText("<- 解密");
        panel1.add(decryptButton);
        final JLabel label5 = new JLabel();
        label5.setText("密文：");
        panel.add(label5, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane4 = new JScrollPane();
        panel.add(scrollPane4, new GridConstraints(5, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        cipherTextArea = new JTextArea();
        cipherTextArea.setLineWrap(true);
        cipherTextArea.setRows(6);
        scrollPane4.setViewportView(cipherTextArea);
        cipherEncodeComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        defaultComboBoxModel2.addElement("HEX");
        defaultComboBoxModel2.addElement("BASE64");
        cipherEncodeComboBox.setModel(defaultComboBoxModel2);
        panel.add(cipherEncodeComboBox, new GridConstraints(5, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel.add(spacer1, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

    private JTextArea area(int rows) {
        JTextArea t = new JTextArea();
        t.setRows(rows);
        t.setLineWrap(true);
        return t;
    }

    private JScrollPane scroll(JTextArea t) {
        return new JScrollPane(t);
    }

    // Fixed add method satisfying multi-line constraints
    private void add(JPanel p, Component comp, GridBagConstraints c, int x, int y, int w, double wx) {
        GridBagConstraints curr = (GridBagConstraints) c.clone();
        curr.gridx = x;
        curr.gridy = y;
        curr.gridwidth = w;
        curr.weightx = wx;
        if (comp instanceof JScrollPane) {
            curr.fill = GridBagConstraints.BOTH;
            curr.weighty = 1.0;
        }
        p.add(comp, curr);
    }

}
