package alg.bc.gui.view.viewSm9;

import alg.bc.gui.view.TabSm9;
import alg.bc.gui.util.EncodeSwitchBinder;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import lombok.Data;

import javax.swing.*;
import java.awt.*;

@Data
public class ViewSm9Kgc {
    private JPanel panel;
    private JComboBox<String> keyEncodeComboBox;
    private JTextField kgcUserIdTextField;
    private JButton genEncMasterButton;
    private JButton genSignMasterButton;
    private JButton deriveEncSkButton;
    private JButton deriveSignSkButton;
    private JTextArea mskEncTextArea;
    private JTextArea mpkEncTextArea;
    private JTextArea skEncTextArea;
    private JTextArea mskSignTextArea;
    private JTextArea mpkSignTextArea;
    private JTextArea skSignTextArea;

    public void init(TabSm9 parent) {
        // Actions
        genEncMasterButton.setActionCommand("sm9GenEncMaster");
        genEncMasterButton.addActionListener(parent.getAction());
        genSignMasterButton.setActionCommand("sm9GenSignMaster");
        genSignMasterButton.addActionListener(parent.getAction());
        deriveEncSkButton.setActionCommand("sm9DeriveEncSk");
        deriveEncSkButton.addActionListener(parent.getAction());
        deriveSignSkButton.setActionCommand("sm9DeriveSignSk");
        deriveSignSkButton.addActionListener(parent.getAction());

        // Binders
        EncodeSwitchBinder.bind(keyEncodeComboBox, mskEncTextArea, "mskEnc");
        EncodeSwitchBinder.bind(keyEncodeComboBox, mpkEncTextArea, "mpkEnc");
        EncodeSwitchBinder.bind(keyEncodeComboBox, skEncTextArea, "skEnc");
        EncodeSwitchBinder.bind(keyEncodeComboBox, mskSignTextArea, "mskSign");
        EncodeSwitchBinder.bind(keyEncodeComboBox, mpkSignTextArea, "mpkSign");
        EncodeSwitchBinder.bind(keyEncodeComboBox, skSignTextArea, "skSign");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(10, 4, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("编码(密钥)：");
        panel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        keyEncodeComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("HEX");
        defaultComboBoxModel1.addElement("BASE64");
        keyEncodeComboBox.setModel(defaultComboBoxModel1);
        panel.add(keyEncodeComboBox, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("用户ID：");
        panel.add(label2, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        kgcUserIdTextField = new JTextField();
        kgcUserIdTextField.setText("user@example.com");
        panel.add(kgcUserIdTextField, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        genEncMasterButton = new JButton();
        genEncMasterButton.setText("生成主密钥(加密)");
        panel.add(genEncMasterButton, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        genSignMasterButton = new JButton();
        genSignMasterButton.setText("生成主密钥(签名)");
        panel.add(genSignMasterButton, new GridConstraints(1, 2, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("加密主密钥(msk)：");
        panel.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel.add(scrollPane1, new GridConstraints(2, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        mskEncTextArea = new JTextArea();
        mskEncTextArea.setLineWrap(true);
        mskEncTextArea.setRows(4);
        scrollPane1.setViewportView(mskEncTextArea);
        final JLabel label4 = new JLabel();
        label4.setText("加密主公钥(mpk)：");
        panel.add(label4, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane2 = new JScrollPane();
        panel.add(scrollPane2, new GridConstraints(3, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        mpkEncTextArea = new JTextArea();
        mpkEncTextArea.setLineWrap(true);
        mpkEncTextArea.setRows(4);
        scrollPane2.setViewportView(mpkEncTextArea);
        deriveEncSkButton = new JButton();
        deriveEncSkButton.setText("派生用户私钥(加密)");
        panel.add(deriveEncSkButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("用户私钥(sk)：");
        panel.add(label5, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane3 = new JScrollPane();
        panel.add(scrollPane3, new GridConstraints(4, 2, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        skEncTextArea = new JTextArea();
        skEncTextArea.setLineWrap(true);
        skEncTextArea.setRows(4);
        scrollPane3.setViewportView(skEncTextArea);
        final JSeparator separator1 = new JSeparator();
        panel.add(separator1, new GridConstraints(5, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label6 = new JLabel();
        label6.setText("签名主密钥(msk)：");
        panel.add(label6, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane4 = new JScrollPane();
        panel.add(scrollPane4, new GridConstraints(6, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        mskSignTextArea = new JTextArea();
        mskSignTextArea.setLineWrap(true);
        mskSignTextArea.setRows(4);
        scrollPane4.setViewportView(mskSignTextArea);
        final JLabel label7 = new JLabel();
        label7.setText("签名主公钥(mpk)：");
        panel.add(label7, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane5 = new JScrollPane();
        panel.add(scrollPane5, new GridConstraints(7, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        mpkSignTextArea = new JTextArea();
        mpkSignTextArea.setLineWrap(true);
        mpkSignTextArea.setRows(4);
        scrollPane5.setViewportView(mpkSignTextArea);
        deriveSignSkButton = new JButton();
        deriveSignSkButton.setText("派生用户私钥(签名)");
        panel.add(deriveSignSkButton, new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label8 = new JLabel();
        label8.setText("用户私钥(sk)：");
        panel.add(label8, new GridConstraints(8, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane6 = new JScrollPane();
        panel.add(scrollPane6, new GridConstraints(8, 2, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        skSignTextArea = new JTextArea();
        skSignTextArea.setLineWrap(true);
        skSignTextArea.setRows(4);
        scrollPane6.setViewportView(skSignTextArea);
        final Spacer spacer1 = new Spacer();
        panel.add(spacer1, new GridConstraints(9, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

    private JTextArea area(int rows) {
        JTextArea t = new JTextArea();
        t.setRows(rows);
        t.setLineWrap(true);
        return t;
    }

    private JScrollPane scroll(JTextArea t) {
        return new JScrollPane(t);
    }

    private void add(JPanel p, Component comp, GridBagConstraints c, int x, int y, int w, double wx) {
        GridBagConstraints curr = (GridBagConstraints) c.clone();
        curr.gridx = x;
        curr.gridy = y;
        curr.gridwidth = w;
        curr.weightx = wx;
        if (comp instanceof JScrollPane) {
            curr.fill = GridBagConstraints.BOTH;
            curr.weighty = 1.0; // Allow vertical expansion
        }
        p.add(comp, curr);
    }

}
