package alg.bc.gui.view.viewSm2;

import alg.bc.gui.view.TabSm2;
import alg.bc.gui.util.EncodeSwitchBinder;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import lombok.Data;

import javax.swing.*;
import java.awt.*;

@Data
public class ViewSm2Encrypt {
    private JPanel sm2EncryptPanel;
    private JComboBox pubKeyTypeComboBox;
    private JComboBox dataTypeComboBox;
    private JRadioButton c1C3C2RadioButton;
    private JRadioButton c1C2C3RadioButton;
    private JButton encryptButton;
    private JComboBox cipherDatacomboBox;
    private JButton resetButton;
    private JTextArea pubKeyArea;
    private JTextArea dataArea;
    private JTextArea cipherDataArea;

    public void init(TabSm2 parent) {
        encryptButton.setActionCommand("sm2Encrypt");
        encryptButton.addActionListener(parent.getAction());
        resetButton.setActionCommand("resetForm");
        resetButton.addActionListener(parent.getAction());

        EncodeSwitchBinder.bind(pubKeyTypeComboBox, pubKeyArea, "公钥");
        EncodeSwitchBinder.bind(dataTypeComboBox, dataArea, "数据");
        EncodeSwitchBinder.bind(cipherDatacomboBox, cipherDataArea, "密文");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        sm2EncryptPanel = new JPanel();
        sm2EncryptPanel.setLayout(new GridLayoutManager(5, 19, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("公钥：");
        sm2EncryptPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pubKeyTypeComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("HEX");
        defaultComboBoxModel1.addElement("BASE64");
        pubKeyTypeComboBox.setModel(defaultComboBoxModel1);
        sm2EncryptPanel.add(pubKeyTypeComboBox, new GridConstraints(0, 17, 1, 2, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("数据：");
        sm2EncryptPanel.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        dataTypeComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        defaultComboBoxModel2.addElement("UTF-8");
        defaultComboBoxModel2.addElement("HEX");
        defaultComboBoxModel2.addElement("BASE64");
        dataTypeComboBox.setModel(defaultComboBoxModel2);
        sm2EncryptPanel.add(dataTypeComboBox, new GridConstraints(1, 17, 1, 2, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("密文格式：");
        sm2EncryptPanel.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        c1C3C2RadioButton = new JRadioButton();
        c1C3C2RadioButton.setSelected(true);
        c1C3C2RadioButton.setText("C1C3C2");
        sm2EncryptPanel.add(c1C3C2RadioButton, new GridConstraints(2, 1, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        c1C2C3RadioButton = new JRadioButton();
        c1C2C3RadioButton.setText("C1C2C3");
        sm2EncryptPanel.add(c1C2C3RadioButton, new GridConstraints(2, 4, 1, 9, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("密文：");
        sm2EncryptPanel.add(label4, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cipherDatacomboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel3 = new DefaultComboBoxModel();
        defaultComboBoxModel3.addElement("HEX");
        defaultComboBoxModel3.addElement("BASE64");
        cipherDatacomboBox.setModel(defaultComboBoxModel3);
        sm2EncryptPanel.add(cipherDatacomboBox, new GridConstraints(3, 17, 1, 2, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        encryptButton = new JButton();
        encryptButton.setText("加密");
        sm2EncryptPanel.add(encryptButton, new GridConstraints(4, 0, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pubKeyArea = new JTextArea();
        pubKeyArea.setLineWrap(true);
        sm2EncryptPanel.add(pubKeyArea, new GridConstraints(0, 1, 1, 16, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 50), null, 0, false));
        dataArea = new JTextArea();
        dataArea.setLineWrap(true);
        sm2EncryptPanel.add(dataArea, new GridConstraints(1, 1, 1, 16, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 50), null, 0, false));
        cipherDataArea = new JTextArea();
        cipherDataArea.setLineWrap(true);
        sm2EncryptPanel.add(cipherDataArea, new GridConstraints(3, 1, 1, 16, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 50), null, 0, false));
        resetButton = new JButton();
        resetButton.setText("重置");
        sm2EncryptPanel.add(resetButton, new GridConstraints(4, 6, 1, 8, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(c1C2C3RadioButton);
        buttonGroup.add(c1C3C2RadioButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return sm2EncryptPanel;
    }

}
