package alg.bc.gui.view.viewSm2;

import alg.bc.gui.view.TabSm2;
import alg.bc.gui.util.EncodeSwitchBinder;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import lombok.Data;

import javax.swing.*;
import javax.swing.text.JTextComponent;
import java.awt.*;

@Data
public class ViewSm2GenerateKey {
    private JPanel sm2GenerateKeyPanel;
    private JTextArea pubKeyArea;
    private JTextArea prvKeyArea;
    private JButton generateSm2KeyBtn;
    private JRadioButton hexRadioButton;
    private JRadioButton base64RadioButton;

    public void init(TabSm2 parent) {
        generateSm2KeyBtn.setActionCommand("generateSm2Key");
        generateSm2KeyBtn.addActionListener(parent.getAction());

        EncodeSwitchBinder.bindHexBase64(hexRadioButton, base64RadioButton,
                new JTextComponent[]{pubKeyArea, prvKeyArea},
                "密钥");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        sm2GenerateKeyPanel = new JPanel();
        sm2GenerateKeyPanel.setLayout(new GridLayoutManager(4, 5, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("公钥：");
        sm2GenerateKeyPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pubKeyArea = new JTextArea();
        pubKeyArea.setColumns(50);
        pubKeyArea.setLineWrap(true);
        pubKeyArea.setRows(10);
        sm2GenerateKeyPanel.add(pubKeyArea, new GridConstraints(0, 1, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("私钥：");
        sm2GenerateKeyPanel.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        prvKeyArea = new JTextArea();
        prvKeyArea.setColumns(50);
        prvKeyArea.setLineWrap(true);
        prvKeyArea.setRows(10);
        sm2GenerateKeyPanel.add(prvKeyArea, new GridConstraints(1, 1, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("编码：");
        sm2GenerateKeyPanel.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        hexRadioButton = new JRadioButton();
        hexRadioButton.setSelected(true);
        hexRadioButton.setText("HEX");
        sm2GenerateKeyPanel.add(hexRadioButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        base64RadioButton = new JRadioButton();
        base64RadioButton.setText("BASE64");
        sm2GenerateKeyPanel.add(base64RadioButton, new GridConstraints(2, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        generateSm2KeyBtn = new JButton();
        generateSm2KeyBtn.setText("生成");
        sm2GenerateKeyPanel.add(generateSm2KeyBtn, new GridConstraints(3, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(hexRadioButton);
        buttonGroup.add(base64RadioButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return sm2GenerateKeyPanel;
    }

}
