package alg.bc.gui.view.viewSm2;

import alg.bc.gui.view.TabSm2;
import alg.bc.gui.util.EncodeSwitchBinder;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import lombok.Data;

import javax.swing.*;
import java.awt.*;

@Data
public class ViewSm2Decrypt {
    private JPanel sm2DecryptPanel;
    private JTextArea prvKeyTextArea;
    private JTextArea cipherDataTextArea;
    private JComboBox prvKeyEncodeComboBox;
    private JComboBox cipherTpeComboBox;
    private JTextArea dataTextArea;
    private JComboBox dataTypeComboBox;
    private JButton decryptButton;
    private JButton resetButton;
    private JRadioButton c1C3C2RadioButton;
    private JRadioButton c1C2C3RadioButton;

    public void init(TabSm2 parent) {
        decryptButton.setActionCommand("sm2Decrypt");
        decryptButton.addActionListener(parent.getAction());
        resetButton.setActionCommand("resetForm");
        resetButton.addActionListener(parent.getAction());

        EncodeSwitchBinder.bind(prvKeyEncodeComboBox, prvKeyTextArea, "私钥");
        EncodeSwitchBinder.bind(cipherTpeComboBox, cipherDataTextArea, "密文");
        EncodeSwitchBinder.bind(dataTypeComboBox, dataTextArea, "数据");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        sm2DecryptPanel = new JPanel();
        sm2DecryptPanel.setLayout(new GridLayoutManager(5, 4, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("私钥：");
        sm2DecryptPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        prvKeyTextArea = new JTextArea();
        prvKeyTextArea.setLineWrap(true);
        sm2DecryptPanel.add(prvKeyTextArea, new GridConstraints(0, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 50), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("密文：");
        sm2DecryptPanel.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cipherDataTextArea = new JTextArea();
        cipherDataTextArea.setLineWrap(true);
        sm2DecryptPanel.add(cipherDataTextArea, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 50), null, 0, false));
        prvKeyEncodeComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("HEX");
        defaultComboBoxModel1.addElement("BASE64");
        prvKeyEncodeComboBox.setModel(defaultComboBoxModel1);
        sm2DecryptPanel.add(prvKeyEncodeComboBox, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cipherTpeComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        defaultComboBoxModel2.addElement("HEX");
        defaultComboBoxModel2.addElement("BASE64");
        cipherTpeComboBox.setModel(defaultComboBoxModel2);
        sm2DecryptPanel.add(cipherTpeComboBox, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("数据：");
        sm2DecryptPanel.add(label3, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        dataTextArea = new JTextArea();
        dataTextArea.setLineWrap(true);
        sm2DecryptPanel.add(dataTextArea, new GridConstraints(3, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(400, 50), null, 0, false));
        dataTypeComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel3 = new DefaultComboBoxModel();
        defaultComboBoxModel3.addElement("UTF-8");
        defaultComboBoxModel3.addElement("HEX");
        defaultComboBoxModel3.addElement("BASE64");
        dataTypeComboBox.setModel(defaultComboBoxModel3);
        sm2DecryptPanel.add(dataTypeComboBox, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        decryptButton = new JButton();
        decryptButton.setText("解密");
        sm2DecryptPanel.add(decryptButton, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        resetButton = new JButton();
        resetButton.setText("重置");
        sm2DecryptPanel.add(resetButton, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("密文格式：");
        sm2DecryptPanel.add(label4, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        c1C3C2RadioButton = new JRadioButton();
        c1C3C2RadioButton.setSelected(true);
        c1C3C2RadioButton.setText("C1C3C2");
        sm2DecryptPanel.add(c1C3C2RadioButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        c1C2C3RadioButton = new JRadioButton();
        c1C2C3RadioButton.setText("C1C2C3");
        sm2DecryptPanel.add(c1C2C3RadioButton, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(c1C3C2RadioButton);
        buttonGroup.add(c1C2C3RadioButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return sm2DecryptPanel;
    }

}
